version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app: ## nome do serviço
    build: . ## localização do dockerfile
    depends_on:
      - db
    command: ["/bin/sh", "./run.sh"] ## comando a executar
    ports:
      - "3333:3333" ## redirecionamento de porta quando chegar alguma requisição na porta 3333 chama o container na porta 3333
    volumes: 
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    networks:
      - backend
    environment:
      NODE_ENV: development
    env_file:
      - .env
networks:
  backend:
    driver: "bridge"
volumes:
  pgdata: